### ISSUE TITLE
build ustl with clang on Linux

### ISSUE THREAD

**Issue by hoangmle** [msharov/ustl#79]
Hi,

On Ubuntu 14.04 (clang 3.4, gcc 4.8.4) and Fedora 22 (clang 3.5, gcc 5.3.1):
`CC=clang CXX=clang++ ./configure --libdir=path/to/libsupc++.a` (without --libdir it searches for libcxxabi when CC=clang)
`make` works fine,
`make check` however shows quite a few diffs.

Is such configuration supposed to work? Thanks!

**Comment by msharov** [comment]
I can compile with clang just fine with no errors or test failures. Please attach the output of make check.

**Comment by hoangmle** [comment]
Ah sorry, the option `--without-mxx` is also needed. Below is the output of `make check` (full log https://travis-ci.org/hoangmle/ustl/jobs/293066809, I wrote a simple Travis CI script in my fork for this, if you think CI is useful I can add a PR).

```
Running build verification tests:
Running .o/test/algos
43c43
< { 15 16 17 18 1 2 3 4 5 6 7 8 9 10 10 11 12 13 13 14 }
---
> { 15 1 10 11 10 10 11 10 10 11 10 10 11 12 10 11 12 13 13 14 }
100c100
< { 2 4 6 8 10 10 12 14 16 18 1 3 5 7 9 11 13 13 15 17 }
---
> { 2 4 6 10 10 10 12 14 18 18 1 3 5 7 9 11 13 13 15 17 }
102c102
< { 2 4 6 8 10 10 12 14 16 18 1 3 5 7 9 11 13 13 15 17 }
---
> { 2 4 6 10 10 10 12 14 18 18 1 3 5 7 9 11 13 13 15 17 }
Running .o/test/array
Running .o/test/btset
Running .o/test/chron
20c20
< Tue Jan  1 00:42:00 1980
---
> Tue Jan  1 05:42:00 1980
Running .o/test/cmlnk
Running .o/test/couts
Running .o/test/enuma
Running .o/test/fstrm
Running .o/test/funct
Running .o/test/llist
Running .o/test/macro
Running .o/test/maptt
Binary files test/maptt.std and .o/test/maptt.out differ
Running .o/test/matrx
Running .o/test/mblck
Running .o/test/mlink
Running .o/test/mumap
22,23c22,23
< Barbara	- $47000
< Gail	- $47000
---
> Barb	- $47000
> BigBoss	- $99000
27,29c27,29
< Barbara	- $47000
< Gail	- $47000
< Mary	- $47000
---
> Barb	- $47000
> BigBoss	- $99000
> BigBoss	- $99000
Running .o/test/muset
7c7
< erase(3):	{ 1 1 1 1 2 4 4 6 8 9 }
---
> erase(3):	{ 1 1 1 1 2 4 8 6 8 9 }
Running .o/test/obstm
Running .o/test/ovect
23c23
< 21 22 23 24 25 26 27 
---
> 21 22 23 24 25 26 27 43 44 
Running .o/test/priqu
Running .o/test/simda
Running .o/test/smptr
Running .o/test/sstrm
Running .o/test/stack
Running .o/test/strms
Running .o/test/strng
15,17c15,17
< erase(5,find(9)-5)	123459012345678901234567890
< erase(5,5)		1234545678901234567890
< push_back('x')		1234545678901234567890x
---
> erase(5,find(9)-5)	123459012348901234234567890
> erase(5,5)		1234543423456567897890
> push_back('x')		1234543423456567897890x
19,20c19,20
< insert(10,#)		1234545678#901234567890
< replace(0,5,@)		@45678#901234567890
---
> insert(10,#)		1234543423#456567897890
> replace(0,5,@)		@434565678977897890
Running .o/test/strvc
Running .o/test/trait
Running .o/test/tuple
Running .o/test/typel
Running .o/test/utf8f
11c11
< Erasing 2 characters after '2':  1234 49 50 3456 4567 2345 51 52 53 54 55 56 57 48
---
> Erasing 2 characters after '2':  1234 49 50 2345 51 52 53 54 55 56 57 52 53 54 55 56 57 48
Running .o/test/utils
Running .o/test/vectr
5,7c5,7
< (2,3,4,5,6,7,8,9,10,11,12,13,13,14,15,16,17)
< (2,3,4,5,6,777,8,9,10,11,666,666,666,12,13,13,14,15,16,17)
< (2,3,4,5,6,777,8,9,10,11,666,666,666,12,13)
---
> (2,3,5,6,7,9,9,10,12,13,13,13,15,15,16,17,17)
> (2,3,5,6,7,777,9,10,12,13,666,666,666,13,13,15,15,16,17,17)
> (2,3,5,6,7,777,9,10,12,13,666,666,666,13,13)
```

**Comment by msharov** [comment]
To clarify: the check failures happen only with --without-mmx, right? Does everything work without that flag?
I am still unable to reproduce any problems here; I'll just poke around blindly awhile...

**Comment by msharov** [comment]
Ok, found the problem. Fixed by commit 731d16978e0912ca6a59effd12716b36cc70dd34

**Comment by hoangmle** [comment]
Thanks! There is still a small issue with test/chron (that happens with gcc as well):
```
Running .o/test/chron
20c20
< Tue Jan  1 00:42:00 1980
---
> Tue Jan  1 06:42:00 1980
``` 
Would you also consider to update the configure script so that it works out-of-the-box with clang on Linux?

**Comment by msharov** [comment]
Chrono test fixed by b78105aec6c6c70051bc1d16b8c335cb09e5c71d.
As for the configure test, see issue #3. Debian-based distributions do not follow the Linux filesystem standard, and provide no way for configure to locate platform headers and libraries. I really don't know how to fix it, or whether it should be fixed.

**Comment by hoangmle** [comment]
I still get a diff for chrono test.
On my local machine:
```
20c20
< Tue Jan  1 00:42:00 1980
---
> Tue Jan  1 12:42:00 1980
```
On Travis CI:
```
20c20
< Tue Jan  1 00:42:00 1980
---
> Tue Jan  1 10:42:00 1980
```

For the other issue: `clang -print-libgcc-file-name` prints the library path for libgcc.a, where libsupc++.a should also to be found. Would that be a viable solution?

**Comment by msharov** [comment]
Oh screw it; commit 3d924813ad86b4d7a3ade38a39327cd5d5248a26 removes the chrono printing test entirely.

I have not heard of -print-libgcc-file-name before. Seems to work, so I'm committing the change in 1ed761b01e908ff8155e045b2630d652c3d1c570. Can't wait to hear how many people will have problems with that one... :)
